import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, BadgeCheck, BookOpenCheck, GraduationCap, ShieldCheck, Users } from "lucide-react";

const Motion = motion;
const fadeUp = { hidden: { opacity: 0, y: 22 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: "easeOut" } } };
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.13 } } };
const values = [
  { icon: ShieldCheck, title: "Trusted learning", text: "Tutor profiles, availability, and class details are managed with clarity before students book." },
  { icon: BookOpenCheck, title: "Focused support", text: "Students can find help by subject, class, course, fee, and learning goals." },
  { icon: Users, title: "Simple coordination", text: "Students, tutors, and admins each get focused tools for a smoother learning experience." },
];

const AboutUs = () => {
  const navigate = useNavigate();
  const shouldReduceMotion = useReducedMotion();
  const goToRegister = () => navigate("/register");
  const goHome = () => { window.scrollTo({ top: 0, behavior: "auto" }); navigate("/"); };
  const goToCourses = () => { navigate("/#courses"); window.setTimeout(() => document.getElementById("courses")?.scrollIntoView({ behavior: shouldReduceMotion ? "auto" : "smooth" }), 50); };
  useEffect(() => { window.scrollTo({ top: 0, behavior: "auto" }); }, []);

  return (
    <div className="min-h-screen overflow-x-clip bg-white font-sans text-slate-950">
      <header className="sticky top-0 z-50 border-b border-blue-950/5 bg-white/90 backdrop-blur-xl"><nav className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-2.5 sm:px-8 lg:px-12 xl:px-6"><Link to="/" onClick={() => window.scrollTo({ top: 0, behavior: "auto" })} className="flex items-center gap-3"><img src="/ScienceEdu-logo.png" alt="ScienceEdu" className="h-12 w-12 rounded-xl object-cover" /><span className="text-2xl font-extrabold tracking-tight">Science<span className="text-blue-600">Edu</span></span></Link><div className="hidden items-center gap-10 text-[15px] font-semibold text-slate-800 lg:flex"><button onClick={goHome} className="transition hover:text-blue-600">Home</button><Link to="/how-it-works" className="transition hover:text-blue-600">How it Works</Link><button onClick={goToCourses} className="transition hover:text-blue-600">Courses</button><button onClick={goToRegister} className="transition hover:text-blue-600">Find Tutors</button><Link to="/about-us" className="relative text-blue-600">About Us<span className="absolute -bottom-5 left-1/2 h-0.5 w-7 -translate-x-1/2 rounded-full bg-blue-600" /></Link><button onClick={goToRegister} className="transition hover:text-blue-600">Contact</button></div><div className="flex items-center gap-3 sm:gap-4"><Link to="/login" className="hidden rounded-xl border border-blue-500/70 bg-white px-5 py-3 text-sm font-bold text-blue-600 shadow-sm transition hover:-translate-y-0.5 hover:shadow-blue-500/15 sm:inline-flex">Login</Link><Motion.button onClick={goToRegister} whileHover={shouldReduceMotion ? undefined : { y: -2, scale: 1.02 }} whileTap={shouldReduceMotion ? undefined : { scale: 0.98 }} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 to-blue-500 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/25">Register</Motion.button></div></nav></header>
      <main>
        <section className="relative isolate overflow-hidden bg-slate-50 px-5 py-20 sm:px-8 lg:px-12 xl:px-6"><Motion.div aria-hidden="true" className="absolute -right-20 top-0 -z-10 h-96 w-96 rounded-full bg-blue-200/35 blur-3xl" animate={shouldReduceMotion ? undefined : { x: [0, -28, 0], y: [0, 20, 0] }} transition={{ duration: 14, repeat: Infinity, ease: "easeInOut" }} /><Motion.div aria-hidden="true" className="absolute -bottom-24 left-10 -z-10 h-72 w-72 rounded-full bg-sky-200/25 blur-3xl" animate={shouldReduceMotion ? undefined : { x: [0, 22, 0] }} transition={{ duration: 16, repeat: Infinity, ease: "easeInOut" }} /><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><Motion.div initial={shouldReduceMotion ? false : "hidden"} animate="visible" variants={stagger}><Motion.p variants={fadeUp} className="text-sm font-bold uppercase tracking-[0.18em] text-[#2f5f90]">About ScienceEdu</Motion.p><Motion.h1 variants={fadeUp} className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl">Online tutoring built around trust, scheduling, and clear next steps</Motion.h1><Motion.p variants={fadeUp} className="mt-6 text-base leading-8 text-slate-600">ScienceEdu helps students connect with verified tutors, book sessions from real availability, complete payment online, and join live classes through an organized digital learning flow.</Motion.p><Motion.button variants={fadeUp} onClick={goToRegister} whileHover={shouldReduceMotion ? undefined : { y: -3, scale: 1.02 }} whileTap={shouldReduceMotion ? undefined : { scale: 0.98 }} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#1f3f66] px-7 py-4 text-sm font-bold text-white shadow-lg shadow-blue-950/15">Create Student Account <Motion.span animate={shouldReduceMotion ? undefined : { x: [0, 3, 0] }} transition={{ duration: 1.6, repeat: Infinity }}><ArrowRight className="h-4 w-4" /></Motion.span></Motion.button></Motion.div><Motion.article initial={shouldReduceMotion ? false : { opacity: 0, x: 26 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: shouldReduceMotion ? 0 : 0.65, delay: shouldReduceMotion ? 0 : 0.12 }} whileHover={shouldReduceMotion ? undefined : { y: -7 }} className="rounded-[2rem] border border-blue-100 bg-white p-6 shadow-xl shadow-blue-950/5 sm:p-8"><Motion.div whileHover={shouldReduceMotion ? undefined : { rotate: 5, scale: 1.06 }} className="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-[#2f5f90]"><BadgeCheck className="h-7 w-7" /></Motion.div><h2 className="mt-6 text-2xl font-bold">Our mission</h2><p className="mt-4 text-sm leading-7 text-slate-600">We make quality tutoring easier to access by reducing friction between finding a tutor, requesting a time, confirming the class, and joining the session.</p></Motion.article></div></section>
        <section className="bg-white px-5 py-20 sm:px-8 lg:px-12 xl:px-6"><div className="mx-auto max-w-7xl"><Motion.div className="mb-10 max-w-2xl" initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.25 }} variants={fadeUp}><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#2f5f90]">What guides us</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">A platform for students, tutors, and admins</h2></Motion.div><Motion.div className="grid gap-5 md:grid-cols-3" variants={stagger} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.2 }}>{values.map((value) => { const Icon = value.icon; return <Motion.article key={value.title} variants={fadeUp} whileHover={shouldReduceMotion ? undefined : { y: -7, scale: 1.01 }} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition-shadow hover:shadow-xl hover:shadow-blue-950/10"><Motion.div whileHover={shouldReduceMotion ? undefined : { rotate: 5, scale: 1.08 }} className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#2f5f90]"><Icon className="h-6 w-6" /></Motion.div><h3 className="text-lg font-bold">{value.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{value.text}</p></Motion.article>; })}</Motion.div></div></section>
      </main>
    </div>
  );
};
export default AboutUs;
